<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB9Ds5rW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB9Ds5rW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB9Ds5rW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB9Ds5rW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB9Ds5rW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'B9Ds5rW',
    'container.build_id' => 'b065b0a4',
    'container.build_time' => 1599589351,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB9Ds5rW');
